import 'package:freezed_annotation/freezed_annotation.dart';
import 'user.dart';
import 'nazotoki_stage.dart';

part 'home_screen_model.freezed.dart'; // generated by freezed_annotation
part 'home_screen_model.g.dart'; // generated by freezed_annotation

@freezed
class HomeScreenModel with _$HomeScreenModel {

  const factory HomeScreenModel({
    @Default(User.DefaultUser) User loginUser,
    @Default([]) List<NazotokiStage> joinedStageList,
  }) = _HomeScreenModel;

  factory HomeScreenModel.fromJson(Map<String, dynamic> json) => _$HomeScreenModelFromJson(json);

  HomeScreenModel updateUser(User value) => copyWith(
    loginUser: value,
  );

  HomeScreenModel updateJoinedStageList(List<NazotokiStage> list) => copyWith(
    joinedStageList: list,
  );
}
