import 'package:freezed_annotation/freezed_annotation.dart';

part 'nazotoki_event.freezed.dart'; // generated by freezed_annotation
part 'nazotoki_event.g.dart'; // generated by freezed_annotation

@freezed
class NazotokiEvent with _$NazotokiEvent {

  const factory NazotokiEvent({
    required int id,
    required String name,
    required String publisher,
    required String place,
    required String eventType,
    required String description,
    required String imageUrl,
    required String eventUrl,
    required DateTime elapseTime,
    @Default(false) bool isRepeatable,
    required DateTime createdAt,
    required DateTime updatedAt,
  }) = _NazotokiEvent;

  factory NazotokiEvent.fromJson(Map<String, dynamic> json) => _$NazotokiEventFromJson(json);
}
