import 'package:freezed_annotation/freezed_annotation.dart';

part 'nazotoki_stage.freezed.dart'; // generated by freezed_annotation
part 'nazotoki_stage.g.dart'; // generated by freezed_annotation

@freezed
class NazotokiStage with _$NazotokiStage {

  const factory NazotokiStage({
    required int id,
    required int eventId,
    bool? isSceeded,
    required DateTime startTime,
    required DateTime createdAt,
  }) = _NazotokiStage;

  factory NazotokiStage.fromJson(Map<String, dynamic> json) => _$NazotokiStageFromJson(json);
}
