import 'package:freezed_annotation/freezed_annotation.dart';

part 'user.freezed.dart'; // generated by freezed_annotation
part 'user.g.dart'; // generated by freezed_annotation

@freezed
class User with _$User {

  const factory User({
    @Default(0) int id,
    @Default('') String username,
    @Default('') String email,
    @Default(false) bool isPremium,
  }) = _User;

  static const User DefaultUser = User();

  factory User.fromJson(Map<String, dynamic> json) => _$UserFromJson(json);
}
