import 'package:freezed_annotation/freezed_annotation.dart';

part 'user.freezed.dart'; // generated by freezed_annotation
part 'user.g.dart'; // generated by freezed_annotation

@freezed
class User with _$User {

  const factory User({
    required int id,
    required String username,
    required String email,
    @Default(false) bool isPremium,
  }) = _User;

  factory User.fromJson(Map<String, dynamic> json) => _$UserFromJson(json);
}
